### ISSUE TITLE
Pig-Dice 

### ISSUE THREAD

**Issue by keejuneman** [FastC-AI-team-4/Project-mini#2]
## 설명
Pig-Dice 게임을 Python으로 구현하기

## 할일

- [x] dice_roll 구현
- [x] dice 1 이외의 숫자에 대한 점수 누적 구현
- [x] dice 1 일 때 스코어 초기화 구현
- [x] 상대방으로 넘어가는 기능 구현

## 참조
- [Pig-Dice Wiki](https://en.wikipedia.org/wiki/Pig_(dice_game))

**Comment by gacenti** [comment]
고생하셨습니다!ㅎㅎ
